package pl.edu.pjatk.tau.dao;

import org.junit.After;
import org.junit.Before;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.junit.runners.JUnit4;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;

import static org.junit.Assert.assertNotNull;

@RunWith(JUnit4.class)
public class PlayerDaoTest {
    public static String url = "jdbc:hsqldb:hsql://localhost/workdb";

    PlayerDao playerDao;

    @Before
    public void setup() throws SQLException {
        Connection connection = DriverManager.getConnection(url);
        try {
            connection.createStatement()
                    .executeUpdate("CREATE TABLE " +
                            "Player(id bigint GENERATED BY DEFAULT AS IDENTITY, "
                            + "name varchar(50) NOT NULL, "
                            + "armor integer NOT NULL, "
                            + "hp integer NOT NULL)");
        }
        catch (SQLException e) { }
        playerDao = new PlayerDaoJdbcImpl(connection);
    }

    @After
    public void cleanup() throws SQLException {
        Connection connection = DriverManager.getConnection(url);
        try {
            connection.prepareStatement("DELETE FROM Player").executeUpdate();
        }
        catch (SQLException e) { }
    }

    @Test
    public void setConnectionTest() throws SQLException {
        assertNotNull(playerDao.getConnection());
    }

}